# Generated by Django 5.2.12 on 2026-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_sync_payment_request_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrelease",
            name="payment_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="paymentrelease",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Payment"),
                    ("advance", "Advance Payment"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentrelease",
            name="currency",
            field=models.CharField(
                choices=[
                    ("SGD", "SGD"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("JPY", "JPY"),
                    ("CNY", "CNY"),
                    ("HKD", "HKD"),
                    ("TWD", "TWD"),
                    ("MYR", "MYR"),
                    ("THB", "THB"),
                    ("INR", "INR"),
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("CHF", "CHF"),
                    ("SEK", "SEK"),
                    ("NOK", "NOK"),
                    ("DKK", "DKK"),
                    ("AED", "AED"),
                ],
                max_length=3,
            ),
        ),
    ]
