# Generated by Django 5.2.12 on 2026-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrelease_payment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrelease',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_pcm', 'Pending Purchase Type Approver Review'), ('pending_final', 'Pending Final Approver Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
