# Generated by Django 5.2 on 2026-07-24

from django.db import migrations, models


def backfill_sgd_payment_snapshots(apps, schema_editor):
    PaymentRelease = apps.get_model("payments", "PaymentRelease")
    PaymentRelease.objects.filter(
        status="approved",
        currency="SGD",
        approved_amount_sgd__isnull=True,
    ).update(
        approved_amount_sgd=models.F("total_price"),
        approval_fx_rate=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_paymentrelease_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrelease",
            name="approval_fx_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrelease",
            name="approval_fx_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentrelease",
            name="approved_amount_sgd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
            ),
        ),
        migrations.RunPython(
            backfill_sgd_payment_snapshots,
            migrations.RunPython.noop,
        ),
    ]
