# Generated by Django 5.2.12 on 2026-07-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('event_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('from_mailbox', models.EmailField(default='SGRDPR@WAGO.com', max_length=254)),
                ('to_emails', models.TextField(help_text='Semicolon-separated recipient email addresses.')),
                ('cc_emails', models.TextField(blank=True, help_text='Semicolon-separated CC email addresses.')),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('attachment_paths', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('drafted', 'Drafted'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_emailo_status_e850d2_idx'), models.Index(fields=['event_type', 'event_key'], name='core_emailo_event_t_4bbe70_idx')],
            },
        ),
    ]
