# Generated by Django 5.2.12 on 2026-07-22 01:41

from django.db import migrations


def configure_outlook_notification_recipients(apps, schema_editor):
    SystemConfig = apps.get_model("core", "SystemConfig")
    defaults = {
        "notify_li_mei_email": '"limei@wago.com"',
        "notify_jolly_email": '"jolly@wago.com"',
        "notify_jess_email": '"jess@wago.com"',
    }
    legacy_keys = {
        "notify_li_mei_email": "notification_email_limeimei",
        "notify_jolly_email": "notification_email_jolly",
        "notify_jess_email": "notification_email_jess",
    }

    for key, default_value in defaults.items():
        current = SystemConfig.objects.filter(key=key).first()
        legacy = SystemConfig.objects.filter(key=legacy_keys[key]).first()
        value = legacy.value if legacy and legacy.value not in ('""', "", "null") else default_value
        if current is None:
            SystemConfig.objects.create(key=key, value=value, description="Notification email")
        elif current.value in ('""', "", "null"):
            current.value = value
            current.save(update_fields=["value"])

    SystemConfig.objects.filter(
        key__in=[*legacy_keys.values(), "credit_platforms"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailoutbox'),
    ]

    operations = [
        migrations.RunPython(configure_outlook_notification_recipients, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='EmailNotificationLog',
        ),
    ]
