# Generated by Django 5.2.12 on 2026-07-22 01:56

from django.db import migrations, models
from django.db.models import Count


def remove_duplicate_workflow_events(apps, schema_editor):
    EmailOutbox = apps.get_model("core", "EmailOutbox")
    duplicates = (
        EmailOutbox.objects.exclude(event_key="")
        .values("event_type", "event_key")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for duplicate in duplicates:
        rows = EmailOutbox.objects.filter(
            event_type=duplicate["event_type"],
            event_key=duplicate["event_key"],
        ).order_by("created_at", "pk")
        keep_id = rows.values_list("pk", flat=True).first()
        rows.exclude(pk=keep_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_replace_email_notification_log'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_workflow_events, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='emailoutbox',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key', ''), _negated=True), fields=('event_type', 'event_key'), name='unique_outbox_workflow_event'),
        ),
    ]
