# Generated by Django 5.2.12 on 2026-03-19 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('vendor', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('SGD', 'SG$'), ('USD', 'US$'), ('EUR', 'EUR')], max_length=3)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('justification', models.TextField()),
                ('po_required', models.BooleanField(default=False)),
                ('target_payment', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_pcm', 'Pending PCM Review'), ('pending_final', 'Pending Final Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('po_sent', 'PO Sent'), ('ordered', 'Ordered'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('pcm_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pcm_comment', models.TextField(blank=True)),
                ('pcm_decided_at', models.DateTimeField(blank=True, null=True)),
                ('final_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('final_comment', models.TextField(blank=True)),
                ('final_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.expensecategory')),
                ('final_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_reviewed_prs', to=settings.AUTH_USER_MODEL)),
                ('pcm_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcm_reviewed_prs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
