# Generated by Django 5.2.12 on 2026-07-17 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_purchaserequest_execution_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='cancellation_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancellation_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_pr_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancellation_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancellation_decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancellation_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_pr_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_pcm', 'Pending Purchase Type Approver Review'), ('pending_final', 'Pending Final Approver Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancellation_pending', 'Cancellation Requested'), ('cancelled', 'Cancelled'), ('po_sent', 'Legacy PO Sent'), ('ordered', 'Legacy Ordered'), ('completed', 'Legacy Completed')], default='draft', max_length=20),
        ),
    ]
