# Generated by Django 5.2.12 on 2026-07-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_purchaserequest_cancellation_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='planned_payment_count',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text=(
                    "Expected number of payment releases. "
                    "This is a planning estimate only."
                ),
            ),
        ),
    ]
