# Generated by Django 5.2 on 2026-07-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_purchaserequest_planned_payment_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAnnualBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                ("amount_sgd", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("locked", "Locked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_budgets",
                        to="orders.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_project_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fiscal_year", "project__mc_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectannualbudget",
            constraint=models.UniqueConstraint(
                fields=("project", "fiscal_year"),
                name="unique_project_annual_budget",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectannualbudget",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_sgd__gte", 0)),
                name="project_annual_budget_non_negative",
            ),
        ),
    ]
