# Generated by Django 5.2.12 on 2026-03-19 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('pcm_approved', 'PCM Approved'), ('pcm_rejected', 'PCM Rejected'), ('final_approved', 'Final Approved'), ('final_rejected', 'Final Rejected'), ('status_changed', 'Status Changed')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='approvals_a_content_532a88_idx')],
            },
        ),
    ]
