# Generated by Django 5.2.12 on 2026-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pcm_approved', 'Purchase Type Approval Approved'), ('pcm_rejected', 'Purchase Type Approval Rejected'), ('final_approved', 'Final Approver Approved'), ('final_rejected', 'Final Approver Rejected'), ('status_changed', 'Status Changed')], max_length=30),
        ),
    ]
