# Generated by Django 5.2.12 on 2026-04-06 09:53

from django.db import migrations, models


def migrate_legacy_delivery_statuses(apps, schema_editor):
    DeliverySubmission = apps.get_model("deliveries", "DeliverySubmission")
    DeliverySubmission.objects.filter(status="submitted").update(status="fully_delivered")


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysubmission",
            name="delivered_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="deliverysubmission",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="deliverysubmission",
            name="currency",
            field=models.CharField(
                choices=[
                    ("SGD", "SGD"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("JPY", "JPY"),
                    ("CNY", "CNY"),
                    ("HKD", "HKD"),
                    ("TWD", "TWD"),
                    ("MYR", "MYR"),
                    ("THB", "THB"),
                    ("INR", "INR"),
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("CHF", "CHF"),
                    ("SEK", "SEK"),
                    ("NOK", "NOK"),
                    ("DKK", "DKK"),
                    ("AED", "AED"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="deliverysubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("partially_delivered", "Partially Delivered"),
                    ("fully_delivered", "Fully Delivered"),
                    ("short_closed", "Short Closed"),
                    ("saved", "Saved"),
                ],
                default="fully_delivered",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_legacy_delivery_statuses, migrations.RunPython.noop),
    ]
